bind-interfaces

interface=wlan1
listen-address=192.168.16.1
dhcp-range=set:wlan1,192.168.16.10,192.168.16.242,12h
dhcp-option=set:wlan1,3,192.168.16.1 # gateway
dhcp-option=set:wlan1,6,192.168.16.1 # dns
address=/#/192.168.16.1

interface=usb0
listen-address=192.168.42.1
dhcp-range=set:usb0,192.168.42.10,192.168.42.242,12h
dhcp-option=set:usb0,3,192.168.42.1 # gateway
dhcp-option=set:usb0,6 # dns

log-queries
log-dhcp
log-facility=/var/log/dnsmasq.log
