bind-interfaces

interface=usb0
listen-address=192.168.42.1
dhcp-range=set:usb0,192.168.42.10,192.168.42.242,12h
dhcp-option=set:usb0,3,192.168.42.1 # gateway
dhcp-option=set:usb0,6 # dns

log-queries
log-dhcp
log-facility=/var/log/dnsmasq.log
